"""Batch semantic outputs; Event keys are supplied by code, not generated by Agents."""

from pydantic import BaseModel, ConfigDict, Field

from capabilities.event.internal.models import EventCandidateSubmission, EventDisposition, EventIdentityDecision
from capabilities.event.internal.storyline_models import (
    AssociationDecision,
    SignalDecision,
    StorylineEventClassification,
)


class ClassifiedCandidate(EventCandidateSubmission):
    classification: StorylineEventClassification


class ClassifiedEventDraft(BaseModel):
    model_config = ConfigDict(extra="forbid")
    candidates: list[ClassifiedCandidate] = Field(max_length=50)
    no_event: list[EventDisposition]


class BatchIdentityItem(BaseModel):
    model_config = ConfigDict(extra="forbid")
    candidate_key: str
    decision: EventIdentityDecision
    duplicate_of: str | None = None


class BatchIdentityDecision(BaseModel):
    model_config = ConfigDict(extra="forbid")
    events: list[BatchIdentityItem] = Field(max_length=50)


class BatchAssociationItem(AssociationDecision):
    candidate_key: str


class BatchAssociationDecision(BaseModel):
    model_config = ConfigDict(extra="forbid")
    events: list[BatchAssociationItem] = Field(max_length=50)


class BatchSignalItem(SignalDecision):
    candidate_key: str


class BatchSignalDecision(BaseModel):
    model_config = ConfigDict(extra="forbid")
    events: list[BatchSignalItem] = Field(max_length=50)
